[theme]
# Temayı koyu (dark) yapıyoruz
base="dark" 
# Ana renk paletini kurumsal mavide tutuyoruz
primaryColor="#0A7E8C" 
# Arka plan rengini Streamlit'in standart koyu rengi yapıyoruz
backgroundColor="#0E1117"
# Metin rengini açık (beyaz) yapıyoruz
textColor="#FAFAFA" 

[client]
showSidebarNavigation=true

[global]
disableWidgetAriaLabeling=false
